server:
 port: ${port:9091}
# DB 配置
spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  password: root
  username: root
 application:
   name: user-service
# 扫描实体
mybatis:
 type-aliases-package: com.seyong.domain
 # mapper.xml配置文件路径
 mapper-locations: classpath:mapper/*Mapper.xml

#配置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

test: 111
